import Link from "next/link";

export default function Landing() {
  return (
    <main className="bg-blobs relative min-h-screen overflow-hidden">
      <nav className="flex items-center justify-between px-8 py-6">
        <div className="flex items-center gap-2">
          <Logo />
          <span style={{ fontFamily: "var(--font-heading)", fontWeight: 700, fontSize: 22, letterSpacing: "-0.02em" }}>
            SAGE
          </span>
        </div>
      </nav>

      <section className="mx-auto flex max-w-5xl flex-col items-center px-6 pt-16 pb-20 text-center">
        <span
          className="mb-6 rounded-full px-4 py-1.5 text-xs font-semibold uppercase tracking-widest"
          style={{
            background: "rgba(108,92,231,0.12)",
            color: "var(--color-ring)",
            border: "1px solid rgba(108,92,231,0.2)",
          }}
        >
          Socratic Agent for Guided Education
        </span>
        <h1
          style={{
            fontFamily: "var(--font-heading)",
            fontWeight: 700,
            fontSize: "clamp(2.5rem, 1rem + 5vw, 5rem)",
            lineHeight: 1.05,
            letterSpacing: "-0.03em",
          }}
        >
          Learn anything.{" "}
          <span style={{
            background: "linear-gradient(135deg, var(--color-ring), var(--color-secondary))",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
          }}>Grow your brain.</span>
        </h1>
        <p className="mt-5 max-w-2xl text-lg" style={{ opacity: 0.72 }}>
          Tell SAGE a topic — capacitors, photosynthesis, anything — and it builds a
          guided lesson, quizzes you, then plants a node in your personal knowledge graph.
        </p>

        <div className="mt-9 flex flex-wrap items-center justify-center gap-3">
          <Link
            href="/learn"
            className="btn-primary"
            style={{ padding: "14px 28px", fontSize: 16 }}
          >
            Start learning →
          </Link>
          <Link href="/learn" className="btn-ghost" style={{ padding: "14px 24px" }}>
            See the brain
          </Link>
        </div>

        <div className="mt-16 grid w-full grid-cols-1 gap-4 text-left sm:grid-cols-3">
          <Feature
            emoji="💬"
            title="Socratic chat"
            body="A 6-agent swarm guides you with questions, not answers — verified against sources."
          />
          <Feature
            emoji="📚"
            title="On-demand lessons"
            body="Any topic becomes a 4-step lesson plus a quick quiz, generated by Gemini."
          />
          <Feature
            emoji="🧠"
            title="A growing brain"
            body="Mastered topics light up nodes around your brain. Every 15 nodes, it grows."
          />
        </div>
      </section>
    </main>
  );
}

function Feature({ emoji, title, body }: { emoji: string; title: string; body: string }) {
  return (
    <div className="card p-5" style={{ minHeight: 0 }}>
      <div className="text-2xl">{emoji}</div>
      <h3 className="mt-2 text-base" style={{ fontFamily: "var(--font-heading)", fontWeight: 600 }}>{title}</h3>
      <p className="mt-1 text-sm" style={{ opacity: 0.7 }}>{body}</p>
    </div>
  );
}

function Logo() {
  return (
    <svg width={32} height={32} viewBox="0 0 32 32" aria-hidden>
      <defs>
        <linearGradient id="lg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="var(--color-ring)" />
          <stop offset="100%" stopColor="var(--color-secondary)" />
        </linearGradient>
      </defs>
      <rect x="2" y="2" width="28" height="28" rx="9" fill="url(#lg)" />
      <path
        d="M10 20c2 1.5 4 2 6 2s4-.5 6-2M11 13c.7-.7 1.6-1 2.5-1M18.5 12c.9 0 1.8.3 2.5 1"
        stroke="white"
        strokeWidth="2"
        strokeLinecap="round"
        fill="none"
      />
    </svg>
  );
}
