"""
PDF export — renders a SAGE lesson conversation into a clean A4 PDF.
Uses ReportLab canvas directly for precise chat-bubble geometry.
"""
import io
import logging
import re
from typing import Optional

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from app.models.user import User
from app.routers.auth import get_current_user

router = APIRouter(prefix="/export", tags=["export"])
log = logging.getLogger("sage.export")

# A4 in points
_PAGE_W = 595.27
_PAGE_H = 841.89
_MARGIN = 56.69
_CONTENT_W = _PAGE_W - 2 * _MARGIN
_BUBBLE_MAX_W = _CONTENT_W * 0.78
_BUBBLE_PAD = 8
_BUBBLE_RADIUS = 6
_LINE_H = 14
_CAPTION_SIZE = 8

# RGB 0-1
_C_BLUE = (0.13, 0.35, 0.72)
_C_USER_BG = (0.93, 0.93, 0.95)
_C_ASST_BG = (1.0, 1.0, 1.0)
_C_BORDER = (0.82, 0.82, 0.82)
_C_DARK = (0.10, 0.10, 0.10)
_C_LIGHT = (0.45, 0.45, 0.45)


class MessageItem(BaseModel):
    role: str
    content: str


class ExportRequest(BaseModel):
    lesson_id: int
    messages: list[MessageItem]
    title: Optional[str] = None


# ---------------------------------------------------------------------------
# PDF helpers
# ---------------------------------------------------------------------------


def _wrap(text: str, c, font: str, size: int, max_w: float) -> list[str]:
    c.setFont(font, size)
    words = text.split()
    lines: list[str] = []
    cur = ""
    for w in words:
        trial = f"{cur} {w}".strip() if cur else w
        if c.stringWidth(trial, font, size) <= max_w:
            cur = trial
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines or [""]


def _bubble_height(lines: int) -> float:
    return lines * _LINE_H + 2 * _BUBBLE_PAD


def _draw_bubble(c, text: str, y: float, is_user: bool) -> float:
    """Draw a chat bubble starting at top=y. Returns total vertical space consumed."""
    from reportlab.lib.colors import Color

    font, size = "Helvetica", 10
    usable = _BUBBLE_MAX_W - 2 * _BUBBLE_PAD
    lines = _wrap(text, c, font, size, usable)

    actual_w = min(
        max(c.stringWidth(ln, font, size) for ln in lines) + 2 * _BUBBLE_PAD,
        _BUBBLE_MAX_W,
    )
    h = _bubble_height(len(lines))
    bx = (_PAGE_W - _MARGIN - actual_w) if is_user else _MARGIN

    c.setFillColor(Color(*(_C_USER_BG if is_user else _C_ASST_BG)))
    c.setStrokeColor(Color(*_C_BORDER))
    c.setLineWidth(0.5)
    c.roundRect(bx, y - h, actual_w, h, _BUBBLE_RADIUS, fill=1, stroke=1)

    c.setFillColor(Color(*_C_DARK))
    c.setFont(font, size)
    ty = y - _BUBBLE_PAD - _LINE_H + 2
    for ln in lines:
        c.drawString(bx + _BUBBLE_PAD, ty, ln)
        ty -= _LINE_H

    label = "You" if is_user else "SAGE"
    c.setFont("Helvetica-Oblique", _CAPTION_SIZE)
    c.setFillColor(Color(*_C_LIGHT))
    if is_user:
        c.drawRightString(bx + actual_w - _BUBBLE_PAD, y + 2, label)
    else:
        c.drawString(bx + _BUBBLE_PAD, y + 2, label)

    return h + _BUBBLE_PAD + _CAPTION_SIZE + 4


def _key_concepts(messages: list[MessageItem]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for msg in messages:
        if msg.role != "assistant":
            continue
        for m in re.findall(r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,3})\b", msg.content):
            k = m.lower()
            if k not in seen and len(m) > 5:
                seen.add(k)
                result.append(m)
            if len(result) >= 10:
                return result
    return result


def _build_pdf(title: str, messages: list[MessageItem]) -> bytes:
    from reportlab.pdfgen import canvas as rl_canvas
    from reportlab.lib.colors import Color

    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=(_PAGE_W, _PAGE_H))
    y = _PAGE_H - _MARGIN

    # Header
    c.setFillColor(Color(*_C_BLUE))
    c.setFont("Helvetica-Bold", 22)
    c.drawString(_MARGIN, y, "SAGE")
    y -= 26

    c.setFillColor(Color(*_C_DARK))
    c.setFont("Helvetica", 13)
    c.drawString(_MARGIN, y, title)
    y -= 18

    c.setStrokeColor(Color(*_C_BLUE))
    c.setLineWidth(1.5)
    c.line(_MARGIN, y, _PAGE_W - _MARGIN, y)
    y -= 22

    # Messages
    for msg in messages:
        content = msg.content.strip()
        if not content:
            continue
        is_user = msg.role == "user"
        font, size = "Helvetica", 10
        lines = _wrap(content, c, font, size, _BUBBLE_MAX_W - 2 * _BUBBLE_PAD)
        est = _bubble_height(len(lines)) + _BUBBLE_PAD + _CAPTION_SIZE + 8

        if y - est < _MARGIN + 60:
            c.setFont("Helvetica", _CAPTION_SIZE)
            c.setFillColor(Color(*_C_LIGHT))
            c.drawCentredString(_PAGE_W / 2, _MARGIN / 2, "Generated by SAGE — Socratic Agent for Guided Education")
            c.showPage()
            y = _PAGE_H - _MARGIN

        y -= _draw_bubble(c, content, y, is_user) + 4

    # Key concepts
    concepts = _key_concepts(messages)
    if concepts:
        if y < _MARGIN + 120:
            c.showPage()
            y = _PAGE_H - _MARGIN

        y -= 16
        c.setStrokeColor(Color(*_C_BLUE))
        c.setLineWidth(1.0)
        c.line(_MARGIN, y, _PAGE_W - _MARGIN, y)
        y -= 14

        c.setFillColor(Color(*_C_BLUE))
        c.setFont("Helvetica-Bold", 13)
        c.drawString(_MARGIN, y, "Key Concepts")
        y -= 18

        c.setFillColor(Color(*_C_DARK))
        col_w = _CONTENT_W / 2
        for i, concept in enumerate(concepts):
            col = i % 2
            x = _MARGIN + col * col_w
            c.setFont("Helvetica-Bold", 10)
            c.drawString(x, y, f"• {concept}")
            if col == 1:
                y -= 16
        if len(concepts) % 2 != 0:
            y -= 16

    # Footer
    c.setFont("Helvetica", _CAPTION_SIZE)
    c.setFillColor(Color(*_C_LIGHT))
    c.drawCentredString(_PAGE_W / 2, _MARGIN / 2, "Generated by SAGE — Socratic Agent for Guided Education")

    c.save()
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------


@router.post("/pdf")
async def export_pdf(
    req: ExportRequest,
    user: User = Depends(get_current_user),
) -> StreamingResponse:
    """Build and stream an A4 PDF of the lesson conversation."""
    title = req.title or f"SAGE Lesson #{req.lesson_id}"
    try:
        pdf_bytes = _build_pdf(title, req.messages)
    except Exception as exc:
        log.error("PDF build failed for user %s lesson %s: %s", user.id, req.lesson_id, exc)
        raise

    safe = re.sub(r"[^\w\s-]", "", title)[:40].strip().replace(" ", "-").lower()
    filename = f"sage-lesson-{safe}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
