"""initial schema

Revision ID: 4169bfdde374
Revises: 
Create Date: 2026-04-10 21:32:43.069581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — migration references sqlmodel.sql.sqltypes.AutoString


# revision identifiers, used by Alembic.
revision: str = '4169bfdde374'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learningpath',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learningpath_slug'), 'learningpath', ['slug'], unique=True)
    op.create_table('project',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hero_emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learning_outcomes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concepts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('architecture_mermaid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('demo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('demo_embed', sa.Boolean(), nullable=False),
    sa.Column('repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setup_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenges', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_lesson_slugs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_slug'), 'project', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('coursedraft',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coursedraft_user_id'), 'coursedraft', ['user_id'], unique=False)
    op.create_table('dailyusage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    op.create_index(op.f('ix_dailyusage_date'), 'dailyusage', ['date'], unique=False)
    op.create_index(op.f('ix_dailyusage_user_id'), 'dailyusage', ['user_id'], unique=False)
    op.create_table('explorationsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explorationsession_user_id'), 'explorationsession', ['user_id'], unique=False)
    op.create_table('generatedcurriculum',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learning_goals', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level_range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('personalization_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phases', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gaps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generatedcurriculum_user_id'), 'generatedcurriculum', ['user_id'], unique=False)
    op.create_table('module',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learning_path_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learningpath.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('explorationmessage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['explorationsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explorationmessage_session_id'), 'explorationmessage', ['session_id'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concepts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vimeo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_kb', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sources_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skillassessment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('background_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overall_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overall_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_dimensions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strengths', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gaps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_module_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommendation_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommended_module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skillassessment_user_id'), 'skillassessment', ['user_id'], unique=False)
    op.create_table('conceptpage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('simple_definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('why_it_matters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detailed_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analogy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('real_world_example', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('misconceptions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_takeaways', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_concepts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('further_reading', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lesson_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conceptpage_topic'), 'conceptpage', ['topic'], unique=False)
    op.create_table('quizsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lesson_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizsession_user_id'), 'quizsession', ['user_id'], unique=False)
    op.create_table('tutorsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lesson_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutorsession_lesson_id'), 'tutorsession', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_tutorsession_user_id'), 'tutorsession', ['user_id'], unique=False)
    op.create_table('userlessonprogress',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lesson_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id')
    )
    op.create_index(op.f('ix_userlessonprogress_lesson_id'), 'userlessonprogress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_userlessonprogress_user_id'), 'userlessonprogress', ['user_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lesson_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['tutorsession.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_lesson_id'), 'chatmessage', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_session_id'), 'chatmessage', ['session_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_user_id'), 'chatmessage', ['user_id'], unique=False)
    op.create_table('quizquestion',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_option_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quizsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizquestion_session_id'), 'quizquestion', ['session_id'], unique=False)
    op.create_table('quizanswer',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_option_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quizquestion.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['quizsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizanswer_question_id'), 'quizanswer', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizanswer_session_id'), 'quizanswer', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizanswer_session_id'), table_name='quizanswer')
    op.drop_index(op.f('ix_quizanswer_question_id'), table_name='quizanswer')
    op.drop_table('quizanswer')
    op.drop_index(op.f('ix_quizquestion_session_id'), table_name='quizquestion')
    op.drop_table('quizquestion')
    op.drop_index(op.f('ix_chatmessage_user_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_session_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_lesson_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_userlessonprogress_user_id'), table_name='userlessonprogress')
    op.drop_index(op.f('ix_userlessonprogress_lesson_id'), table_name='userlessonprogress')
    op.drop_table('userlessonprogress')
    op.drop_index(op.f('ix_tutorsession_user_id'), table_name='tutorsession')
    op.drop_index(op.f('ix_tutorsession_lesson_id'), table_name='tutorsession')
    op.drop_table('tutorsession')
    op.drop_index(op.f('ix_quizsession_user_id'), table_name='quizsession')
    op.drop_table('quizsession')
    op.drop_index(op.f('ix_conceptpage_topic'), table_name='conceptpage')
    op.drop_table('conceptpage')
    op.drop_index(op.f('ix_skillassessment_user_id'), table_name='skillassessment')
    op.drop_table('skillassessment')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_explorationmessage_session_id'), table_name='explorationmessage')
    op.drop_table('explorationmessage')
    op.drop_table('module')
    op.drop_index(op.f('ix_generatedcurriculum_user_id'), table_name='generatedcurriculum')
    op.drop_table('generatedcurriculum')
    op.drop_index(op.f('ix_explorationsession_user_id'), table_name='explorationsession')
    op.drop_table('explorationsession')
    op.drop_index(op.f('ix_dailyusage_user_id'), table_name='dailyusage')
    op.drop_index(op.f('ix_dailyusage_date'), table_name='dailyusage')
    op.drop_table('dailyusage')
    op.drop_index(op.f('ix_coursedraft_user_id'), table_name='coursedraft')
    op.drop_table('coursedraft')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_project_slug'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_learningpath_slug'), table_name='learningpath')
    op.drop_table('learningpath')
    # ### end Alembic commands ###
